name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 17 * * 6'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
          - java: 17
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - run: sbt -v test scripted
    - run: sbt -v "++ 3.x" test scripted
      if: matrix.java != 8
